# Generated by Django 2.1.2 on 2019-01-13 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(default=2018)),
                ('begin_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('contract_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pymentorat.Contract')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Discipline',
                'verbose_name_plural': 'Disciplines',
            },
        ),
        migrations.CreateModel(
            name='EDA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(default=2018)),
                ('classe', models.CharField(max_length=12)),
                ('inscription_date', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymentorat.Discipline')),
            ],
            options={
                'verbose_name': "Elève demandeur d'aide",
                'verbose_name_plural': "Elèves demandeurs d'aide",
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(default=2018)),
                ('classe', models.CharField(max_length=12)),
                ('inscription_date', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymentorat.Discipline')),
            ],
            options={
                'verbose_name': 'Elève mentor',
                'verbose_name_plural': 'Elèves mentors',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tel', models.CharField(blank=True, max_length=13, null=True)),
                ('portable', models.CharField(blank=True, max_length=13, null=True)),
                ('id_OD', models.CharField(max_length=12, unique=True)),
            ],
            options={
                'verbose_name': 'Elève',
                'verbose_name_plural': 'Elèves',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('id_OD', models.CharField(max_length=12, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Maître',
                'verbose_name_plural': 'Maîtres',
            },
        ),
        migrations.AddField(
            model_name='mentor',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymentorat.Student'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymentorat.Teacher'),
        ),
        migrations.AddField(
            model_name='eda',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymentorat.Student'),
        ),
        migrations.AddField(
            model_name='eda',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymentorat.Teacher'),
        ),
        migrations.AddField(
            model_name='contract',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymentorat.Discipline'),
        ),
        migrations.AddField(
            model_name='contract',
            name='eda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymentorat.EDA'),
        ),
        migrations.AddField(
            model_name='contract',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymentorat.Mentor'),
        ),
    ]
