# Generated by Django 2.1.3 on 2018-11-21 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EDA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('classe', models.CharField(max_length=12)),
                ('inscription_date', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField()),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymentorat.Discipline')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('classe', models.CharField(max_length=12)),
                ('inscription_date', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField()),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymentorat.Discipline')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=13)),
                ('portable', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('id_OD', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='mentor',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymentorat.Student'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymentorat.Teacher'),
        ),
        migrations.AddField(
            model_name='eda',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymentorat.Student'),
        ),
        migrations.AddField(
            model_name='eda',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymentorat.Teacher'),
        ),
    ]
