# Generated by Django 2.1.2 on 2019-01-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pymentorat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_OD',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id_OD',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
    ]
