# Generated by Django 2.1.3 on 2018-11-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pymentorat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='id_OD',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='eda',
            name='remark',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='eda',
            name='year',
            field=models.IntegerField(default=2018),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='remark',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='year',
            field=models.IntegerField(default=2018),
        ),
        migrations.AlterField(
            model_name='student',
            name='portable',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='tel',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id_OD',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
