# Generated by Django 2.1.3 on 2018-11-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pymentorat', '0002_auto_20181123_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_OD',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
