# Generated by Django 2.1.2 on 2019-01-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pymentorat', '0002_auto_20190113_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='prenom',
            new_name='vorname',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='prenom',
            new_name='vorname',
        ),
    ]
