# Generated by Django 2.1.5 on 2019-01-16 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pymentorat', '0003_auto_20190113_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(verbose_name='Date de rendez-vous')),
                ('place', models.TextField(default='Devant la salle des maîtres', verbose_name='Lieu de rendez-vous')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Convocation',
                'verbose_name_plural': 'Convocations',
            },
        ),
        migrations.AlterModelOptions(
            name='discipline',
            options={'verbose_name': 'Branche', 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='begin_date',
            field=models.DateField(auto_now_add=True, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='Remarque'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='year',
            field=models.PositiveIntegerField(default=2018, verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='eda',
            name='classe',
            field=models.CharField(max_length=12, verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='eda',
            name='inscription_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription"),
        ),
        migrations.AlterField(
            model_name='eda',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='eda',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='Remarque'),
        ),
        migrations.AlterField(
            model_name='eda',
            name='year',
            field=models.PositiveIntegerField(default=2018, verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='classe',
            field=models.CharField(max_length=12, verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='inscription_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription"),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='Remarque'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='year',
            field=models.PositiveIntegerField(default=2018, verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='student',
            name='portable',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Portable'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tel',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='student',
            name='vorname',
            field=models.CharField(max_length=50, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='vorname',
            field=models.CharField(max_length=50, verbose_name='Prénom'),
        ),
        migrations.AddField(
            model_name='convocation',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pymentorat.Contract'),
        ),
    ]
