# Generated by Django 2.1.5 on 2019-01-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pymentorat', '0005_auto_20190116_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocation',
            name='message',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='convocation',
            name='place',
            field=models.CharField(default='Devant la salle des maîtres', max_length=64, verbose_name='Lieu de rendez-vous'),
        ),
    ]
