# Generated by Django 2.1.5 on 2019-01-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pymentorat', '0006_auto_20190116_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_classe',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Classe actuelle'),
        ),
        migrations.AlterField(
            model_name='convocation',
            name='place',
            field=models.CharField(default='devant la salle des maîtres', max_length=64, verbose_name='Lieu de rendez-vous'),
        ),
    ]
