# Generated by Django 2.1.5 on 2019-01-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pymentorat', '0011_auto_20190128_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='inscription_date',
            field=models.DateField(auto_now_add=True, verbose_name="Date d'inscription"),
        ),
    ]
