# Generated by Django 2.1.5 on 2019-01-30 21:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pymentorat', '0013_auto_20190130_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='begin_date',
            field=models.DateField(default=datetime.datetime(2019, 1, 30, 21, 17, 46, 117717, tzinfo=utc), verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='eda',
            name='inscription_date',
            field=models.DateField(default=datetime.datetime(2019, 1, 30, 21, 17, 46, 117000, tzinfo=utc), verbose_name="Date d'inscription"),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='inscription_date',
            field=models.DateField(default=datetime.datetime(2019, 1, 30, 21, 17, 46, 116316, tzinfo=utc), verbose_name="Date d'inscription"),
        ),
    ]
