# Generated by Django 3.1.6 on 2021-02-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pymentorat', '0015_auto_20190130_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='year',
            field=models.PositiveIntegerField(default=2020, verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='eda',
            name='year',
            field=models.PositiveIntegerField(default=2020, verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='year',
            field=models.PositiveIntegerField(default=2020, verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_OD',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id_OD',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
